Pgm to open an image, display it and retrive its dimensions using opecv

In [1]:
import cv2

In [2]:
img = cv2.imread("myimage.jpg", cv2.IMREAD_COLOR)
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
print("Image Dimension:",img.shape)

Image Dimension: (1443, 1059, 3)


Program to read an input image, convert it into an array of number and display it

In [4]:
print(type(img))

<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr_img=np.array(img)
print("Image Array: ",arr_img)

Image Array:  [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[201 199 188]
  [187 185 174]
  [174 172 161]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[221 220 210]
  [204 203 193]
  [187 186 176]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[226 224 216]
  [208 206 198]
  [189 188 178]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


Program to read a color image and convert it into grayscale

In [16]:
gray_img= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("image",gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img.shape

(1443, 1059, 3)

In [8]:
(h,w)=img.shape[:2]
print("Height: ",h,"\nWidth: ",w)

Height:  1443 
Width:  1059


In [10]:
resized_img = cv2.resize(img, (500, 500))
cv2.imshow("Resized Image", resized_img)
cv2.waitKey(0)
cv2.destroyAllWindows() 